"""Typed data objects shared by Set Weaver agents."""
from __future__ import annotations

from datetime import timedelta
from typing import Iterable, List, Sequence

from pydantic import BaseModel, Field, ValidationError, field_validator, model_validator
from pydantic import FieldValidationInfo


class TrackData(BaseModel):
    """Authoritative representation of a track in the music library."""

    id: str = Field(..., examples=["TRK_00451"])
    artist: str = Field(..., examples=["Daft Punk"])
    title: str = Field(..., examples=["Da Funk"])
    genre: str = Field(..., examples=["French House"])
    bpm: int = Field(..., ge=60, le=220, examples=[111])
    key_camelot: str = Field(..., pattern=r"^[0-9]{1,2}[AB]$", examples=["10A"])
    energy_level: int = Field(..., ge=1, le=10, examples=[8])
    duration_sec: int = Field(..., gt=0, examples=[330])


class TrackFilter(BaseModel):
    """Filter payload passed to the music library tool."""

    bpm_min: int = Field(..., ge=60, le=220)
    bpm_max: int = Field(..., ge=60, le=220)
    genre: str
    key_camelot: str | None = Field(default=None, pattern=r"^[0-9]{1,2}[AB]$")
    energy_min: int | None = Field(default=None, ge=1, le=10)
    energy_max: int | None = Field(default=None, ge=1, le=10)

    @model_validator(mode="before")
    @classmethod
    def _clamp_energy_range(cls, values: dict) -> dict:
        """Prevent upstream tools from breaking validation with out-of-range energy filters."""
        for key in ("energy_min", "energy_max"):
            if key not in values or values[key] is None:
                continue
            values[key] = max(1, min(10, values[key]))
        return values

    @field_validator("bpm_max")
    @classmethod
    def _check_bpm_bounds(cls, value: int, info: FieldValidationInfo) -> int:
        bpm_min = info.data.get("bpm_min")
        if bpm_min is not None and value < bpm_min:
            msg = "bpm_max must be greater than or equal to bpm_min"
            raise ValueError(msg)
        return value

    @field_validator("energy_max")
    @classmethod
    def _check_energy_bounds(cls, value: int | None, info: FieldValidationInfo) -> int | None:
        if value is None:
            return value
        energy_min = info.data.get("energy_min")
        if energy_min is not None and value < energy_min:
            msg = "energy_max must be greater than or equal to energy_min"
            raise ValueError(msg)
        return value


class TransitionProposal(BaseModel):
    """Structured output generated by the Transition Agent."""

    transition_id: str
    track_a_id: str
    track_b_id: str | None = None
    key_compatibility: str
    bpm_change: float
    mix_duration_bars: int
    mixing_technique: str
    suggested_fx: str
    notes_to_dj: str


class SetlistEntry(BaseModel):
    """Single entry in the final setlist report."""

    track_id: str
    track_artist: str
    track_title: str
    genre: str
    bpm: int
    key_camelot: str
    energy_level: int
    start_time: str = Field(..., pattern=r"^[0-9]{2}:[0-9]{2}$")
    mix_out_instructions: TransitionProposal | None = None


class SetlistReport(BaseModel):
    """Top-level report produced by the Strategist."""

    set_title: str
    duration_minutes: int
    setlist: List[SetlistEntry]

    @property
    def total_runtime(self) -> timedelta:
        """Approximate runtime based on track start times."""

        if not self.setlist:
            return timedelta(0)
        last_entry = self.setlist[-1]
        minutes, seconds = map(int, last_entry.start_time.split(":"))
        return timedelta(minutes=minutes, seconds=seconds)


def validate_track_list(data: Iterable[dict]) -> List[TrackData]:
    """Validate tool output and coerce it into TrackData objects."""

    tracks = []
    for item in data:
        tracks.append(TrackData.model_validate(item))
    return tracks


def validate_setlist_report(payload: dict) -> SetlistReport:
    """Validate the Strategist's final JSON setlist report."""

    return SetlistReport.model_validate(payload)


def asdict_sequence(items: Sequence[BaseModel]) -> list[dict]:
    """Convert Pydantic models into plain dicts for tool responses."""

    return [item.model_dump() for item in items]
